-- ============================================================
-- Enterprise Financial Data Platform
-- Transaction Service - Initial Database Schema
-- ============================================================

CREATE TABLE TRANSACTIONS (
                              TRANSACTION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                              TRANSACTION_REFERENCE VARCHAR2(36) NOT NULL,
                              TRANSACTION_TYPE VARCHAR2(20) NOT NULL,

                              SOURCE_ACCOUNT_ID NUMBER,
                              TARGET_ACCOUNT_ID NUMBER,

                              AMOUNT NUMBER(19,2) NOT NULL,
                              CURRENCY VARCHAR2(3) NOT NULL,
                              TRANSACTION_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,

                              DESCRIPTION VARCHAR2(255),
                              FAILURE_REASON VARCHAR2(500),

                              CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                              CONSTRAINT PK_TRANSACTIONS
                                  PRIMARY KEY (TRANSACTION_ID),

                              CONSTRAINT UK_TRANSACTIONS_REFERENCE
                                  UNIQUE (TRANSACTION_REFERENCE),

                              CONSTRAINT CK_TRANSACTIONS_TYPE
                                  CHECK (TRANSACTION_TYPE IN (
                                                              'DEPOSIT', 'WITHDRAWAL', 'TRANSFER'
                                      )),

                              CONSTRAINT CK_TRANSACTIONS_STATUS
                                  CHECK (TRANSACTION_STATUS IN (
                                                                'PENDING', 'COMPLETED', 'FAILED'
                                      )),

                              CONSTRAINT CK_TRANSACTIONS_AMOUNT
                                  CHECK (AMOUNT > 0),

                              CONSTRAINT CK_TRANSACTIONS_CURRENCY
                                  CHECK (REGEXP_LIKE(CURRENCY, '^[A-Z]{3}$', 'c')),

                              CONSTRAINT CK_TRANSACTIONS_ACCOUNTS
                                  CHECK (
                                      (
                                          TRANSACTION_TYPE = 'DEPOSIT'
                                              AND SOURCE_ACCOUNT_ID IS NULL
                                              AND TARGET_ACCOUNT_ID IS NOT NULL
                                          )
                                          OR
                                      (
                                          TRANSACTION_TYPE = 'WITHDRAWAL'
                                              AND SOURCE_ACCOUNT_ID IS NOT NULL
                                              AND TARGET_ACCOUNT_ID IS NULL
                                          )
                                          OR
                                      (
                                          TRANSACTION_TYPE = 'TRANSFER'
                                              AND SOURCE_ACCOUNT_ID IS NOT NULL
                                              AND TARGET_ACCOUNT_ID IS NOT NULL
                                              AND SOURCE_ACCOUNT_ID <> TARGET_ACCOUNT_ID
                                          )
                                      )
);

CREATE INDEX IDX_TRANSACTIONS_SOURCE
    ON TRANSACTIONS (SOURCE_ACCOUNT_ID);

CREATE INDEX IDX_TRANSACTIONS_TARGET
    ON TRANSACTIONS (TARGET_ACCOUNT_ID);

CREATE INDEX IDX_TRANSACTIONS_STATUS
    ON TRANSACTIONS (TRANSACTION_STATUS);

CREATE INDEX IDX_TRANSACTIONS_CREATED
    ON TRANSACTIONS (CREATED_AT);