ALTER TABLE TRANSACTIONS
    ADD (
        IDEMPOTENCY_KEY VARCHAR2(100),
        REQUEST_HASH VARCHAR2(64)
    );

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT UK_TRANSACTIONS_IDEMPOTENCY_KEY
        UNIQUE (IDEMPOTENCY_KEY);