-- ============================================================
-- Enterprise Financial Data Platform
-- Transaction Service - Transaction Status History
-- ============================================================

CREATE TABLE TRANSACTION_STATUS_HISTORY (
                                            STATUS_HISTORY_ID NUMBER
                                                GENERATED BY DEFAULT AS IDENTITY,

                                            TRANSACTION_ID NUMBER NOT NULL,

                                            TRANSACTION_REFERENCE VARCHAR2(36) NOT NULL,

                                            PREVIOUS_STATUS VARCHAR2(30),

                                            NEW_STATUS VARCHAR2(30) NOT NULL,

                                            TRANSITION_SOURCE VARCHAR2(50) NOT NULL,

                                            TRANSITION_REASON VARCHAR2(500),

                                            CORRELATION_ID VARCHAR2(100),

                                            CREATED_AT TIMESTAMP
                                                DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                            CONSTRAINT PK_TRANSACTION_STATUS_HISTORY
                                                PRIMARY KEY (STATUS_HISTORY_ID),

                                            CONSTRAINT FK_TXN_STATUS_HISTORY_TRANSACTION
                                                FOREIGN KEY (TRANSACTION_ID)
                                                    REFERENCES TRANSACTIONS (TRANSACTION_ID),

                                            CONSTRAINT CK_TXN_HISTORY_NEW_STATUS
                                                CHECK (
                                                    NEW_STATUS IN (
                                                                   'PENDING',
                                                                   'PROCESSING',
                                                                   'COMPLETED',
                                                                   'FAILED',
                                                                   'RECONCILIATION_REQUIRED',
                                                                   'MANUAL_REVIEW'
                                                        )
                                                    ),

                                            CONSTRAINT CK_TXN_HISTORY_PREVIOUS_STATUS
                                                CHECK (
                                                    PREVIOUS_STATUS IS NULL
                                                        OR PREVIOUS_STATUS IN (
                                                                               'PENDING',
                                                                               'PROCESSING',
                                                                               'COMPLETED',
                                                                               'FAILED',
                                                                               'RECONCILIATION_REQUIRED',
                                                                               'MANUAL_REVIEW'
                                                        )
                                                    )
);

CREATE INDEX IDX_TXN_HISTORY_TRANSACTION
    ON TRANSACTION_STATUS_HISTORY (TRANSACTION_ID);

CREATE INDEX IDX_TXN_HISTORY_REFERENCE
    ON TRANSACTION_STATUS_HISTORY (TRANSACTION_REFERENCE);

CREATE INDEX IDX_TXN_HISTORY_CREATED_AT
    ON TRANSACTION_STATUS_HISTORY (CREATED_AT);