-- ============================================================
-- Enterprise Financial Data Platform
-- Customer Service - Initial Database Schema
-- ============================================================


-- ============================================================
-- 1. CUSTOMERS TABLE
-- ============================================================

CREATE TABLE CUSTOMERS (
                           CUSTOMER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

                           CUSTOMER_NUMBER VARCHAR2(6) NOT NULL,

                           FIRST_NAME VARCHAR2(100) NOT NULL,

                           LAST_NAME VARCHAR2(100) NOT NULL,

                           EMAIL VARCHAR2(150) NOT NULL,

                           PHONE_NUMBER VARCHAR2(20),

                           DATE_OF_BIRTH DATE,

                           CUSTOMER_STATUS VARCHAR2(20) NOT NULL,

                           CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                           UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                           CONSTRAINT PK_CUSTOMERS
                               PRIMARY KEY (CUSTOMER_ID),

                           CONSTRAINT UK_CUSTOMERS_NUMBER
                               UNIQUE (CUSTOMER_NUMBER),

                           CONSTRAINT UK_CUSTOMERS_EMAIL
                               UNIQUE (EMAIL),

                           CONSTRAINT CK_CUSTOMERS_STATUS
                               CHECK (CUSTOMER_STATUS IN ('ACTIVE', 'INACTIVE'))
);


-- ============================================================
-- 2. CUSTOMER SEARCH / FILTER INDEXES
-- ============================================================

CREATE INDEX IDX_CUSTOMERS_STATUS
    ON CUSTOMERS (CUSTOMER_STATUS);

CREATE INDEX IDX_CUSTOMERS_FIRST_NAME
    ON CUSTOMERS (FIRST_NAME);

CREATE INDEX IDX_CUSTOMERS_LAST_NAME
    ON CUSTOMERS (LAST_NAME);


-- ============================================================
-- 3. CUSTOMER NUMBER SEQUENCE
-- ============================================================

CREATE SEQUENCE CUSTOMER_NUMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- ============================================================
-- 4. CUSTOMER NUMBER GENERATION TRIGGER
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_NUMBER
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
WHEN (NEW.CUSTOMER_NUMBER IS NULL)
BEGIN
    :NEW.CUSTOMER_NUMBER :=
        LPAD(CUSTOMER_NUMBER_SEQ.NEXTVAL, 6, '0');
END;
/