CREATE TABLE CUSTOMER_ADDRESSES (
                                    ADDRESS_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    CUSTOMER_ID NUMBER NOT NULL,

                                    ADDRESS_TYPE VARCHAR2(20) NOT NULL,

                                    ADDRESS_LINE_1 VARCHAR2(150) NOT NULL,
                                    ADDRESS_LINE_2 VARCHAR2(150),

                                    CITY VARCHAR2(100) NOT NULL,
                                    STATE VARCHAR2(50) NOT NULL,
                                    POSTAL_CODE VARCHAR2(20) NOT NULL,
                                    COUNTRY VARCHAR2(100) NOT NULL,

                                    IS_CURRENT NUMBER(1) DEFAULT 1 NOT NULL,

                                    VALID_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                    VALID_TO TIMESTAMP,

                                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                    CONSTRAINT FK_CUSTOMER_ADDRESSES_CUSTOMER
                                        FOREIGN KEY (CUSTOMER_ID)
                                            REFERENCES CUSTOMERS(CUSTOMER_ID),

                                    CONSTRAINT CHK_CUSTOMER_ADDRESS_TYPE
                                        CHECK (ADDRESS_TYPE IN ('HOME', 'MAILING', 'BILLING', 'WORK')),

                                    CONSTRAINT CHK_CUSTOMER_ADDRESS_CURRENT
                                        CHECK (IS_CURRENT IN (0, 1))
);



CREATE INDEX IDX_CUSTOMER_ADDRESSES_CUSTOMER_ID
    ON CUSTOMER_ADDRESSES(CUSTOMER_ID);

CREATE INDEX IDX_CUSTOMER_ADDRESSES_TYPE
    ON CUSTOMER_ADDRESSES(ADDRESS_TYPE);

CREATE INDEX IDX_CUSTOMER_ADDRESSES_CURRENT
    ON CUSTOMER_ADDRESSES(IS_CURRENT);

CREATE INDEX IDX_CUSTOMER_ADDRESSES_CUSTOMER_TYPE
    ON CUSTOMER_ADDRESSES(CUSTOMER_ID, ADDRESS_TYPE);