CREATE UNIQUE INDEX UK_CUSTOMER_CURRENT_ADDRESS_TYPE
    ON CUSTOMER_ADDRESSES (
                           CASE WHEN IS_CURRENT = 1 THEN CUSTOMER_ID END,
                           CASE WHEN IS_CURRENT = 1 THEN ADDRESS_TYPE END
        );