CREATE TABLE CUSTOMER_KYC (
                              KYC_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              CUSTOMER_ID NUMBER NOT NULL,

                              KYC_STATUS VARCHAR2(30) NOT NULL,

                              DOCUMENT_TYPE VARCHAR2(30) NOT NULL,

                              DOCUMENT_NUMBER VARCHAR2(100) NOT NULL,

                              VERIFIED_AT TIMESTAMP NULL,

                              LAST_REVIEWED_AT TIMESTAMP NULL,

                              CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                              UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                              CONSTRAINT FK_CUSTOMER_KYC_CUSTOMER
                                  FOREIGN KEY (CUSTOMER_ID)
                                      REFERENCES CUSTOMERS (CUSTOMER_ID),

                              CONSTRAINT UK_CUSTOMER_KYC_CUSTOMER
                                  UNIQUE (CUSTOMER_ID),

                              CONSTRAINT CHK_CUSTOMER_KYC_STATUS
                                  CHECK (
                                      KYC_STATUS IN (
                                                     'PENDING',
                                                     'VERIFIED',
                                                     'REJECTED',
                                                     'REVIEW_REQUIRED'
                                          )
                                      ),

                              CONSTRAINT CHK_CUSTOMER_KYC_DOCUMENT_TYPE
                                  CHECK (
                                      DOCUMENT_TYPE IN (
                                                        'PASSPORT',
                                                        'DRIVER_LICENSE',
                                                        'STATE_ID',
                                                        'SSN'
                                          )
                                      )
);

CREATE INDEX IDX_CUSTOMER_KYC_STATUS
    ON CUSTOMER_KYC (KYC_STATUS);

CREATE INDEX IDX_CUSTOMER_KYC_DOCUMENT_TYPE
    ON CUSTOMER_KYC (DOCUMENT_TYPE);