-- ============================================================
-- Enterprise Financial Data Platform
-- Account Service - Initial Database Schema
-- ============================================================

CREATE TABLE ACCOUNTS (
                          ACCOUNT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

                          ACCOUNT_NUMBER VARCHAR2(10) NOT NULL,

                          CUSTOMER_ID NUMBER NOT NULL,

                          ACCOUNT_TYPE VARCHAR2(20) NOT NULL,

                          BALANCE NUMBER(19,2) DEFAULT 0 NOT NULL,

                          ACCOUNT_STATUS VARCHAR2(20) NOT NULL,

                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

                          CONSTRAINT PK_ACCOUNTS
                              PRIMARY KEY (ACCOUNT_ID),

                          CONSTRAINT UK_ACCOUNTS_NUMBER
                              UNIQUE (ACCOUNT_NUMBER),

                          CONSTRAINT CK_ACCOUNTS_TYPE
                              CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS', 'CREDIT')),

                          CONSTRAINT CK_ACCOUNTS_STATUS
                              CHECK (ACCOUNT_STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'CLOSED'))
);

CREATE INDEX IDX_ACCOUNTS_CUSTOMER_ID
    ON ACCOUNTS (CUSTOMER_ID);

CREATE INDEX IDX_ACCOUNTS_STATUS
    ON ACCOUNTS (ACCOUNT_STATUS);

CREATE INDEX IDX_ACCOUNTS_TYPE
    ON ACCOUNTS (ACCOUNT_TYPE);

CREATE SEQUENCE ACCOUNT_NUMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ACCOUNTS_NUMBER
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
WHEN (NEW.ACCOUNT_NUMBER IS NULL)
BEGIN
    :NEW.ACCOUNT_NUMBER :=
        LPAD(ACCOUNT_NUMBER_SEQ.NEXTVAL, 10, '0');
END;
/