-- ============================================================
-- Enterprise Financial Data Platform
-- Account Service - Account Balance Operations
-- ============================================================

CREATE TABLE ACCOUNT_BALANCE_OPERATIONS (
                                            BALANCE_OPERATION_ID NUMBER
                                                GENERATED BY DEFAULT AS IDENTITY,

                                            OPERATION_REFERENCE VARCHAR2(150) NOT NULL,

                                            TRANSACTION_REFERENCE VARCHAR2(36) NOT NULL,

                                            ACCOUNT_ID NUMBER NOT NULL,

                                            OPERATION_TYPE VARCHAR2(20) NOT NULL,

                                            AMOUNT NUMBER(19,2) NOT NULL,

                                            BALANCE_BEFORE NUMBER(19,2) NOT NULL,

                                            BALANCE_AFTER NUMBER(19,2) NOT NULL,

                                            REQUEST_HASH VARCHAR2(64) NOT NULL,

                                            DESCRIPTION VARCHAR2(255),

                                            CREATED_AT TIMESTAMP
                                                DEFAULT CURRENT_TIMESTAMP NOT NULL,

                                            CONSTRAINT PK_ACCOUNT_BALANCE_OPERATIONS
                                                PRIMARY KEY (BALANCE_OPERATION_ID),

                                            CONSTRAINT UK_ACCOUNT_BALANCE_OPERATION_REF
                                                UNIQUE (OPERATION_REFERENCE),

                                            CONSTRAINT FK_BALANCE_OPERATION_ACCOUNT
                                                FOREIGN KEY (ACCOUNT_ID)
                                                    REFERENCES ACCOUNTS (ACCOUNT_ID),

                                            CONSTRAINT CK_BALANCE_OPERATION_TYPE
                                                CHECK (
                                                    OPERATION_TYPE IN (
                                                                       'DEBIT',
                                                                       'CREDIT',
                                                                       'REVERSAL'
                                                        )
                                                    ),

                                            CONSTRAINT CK_BALANCE_OPERATION_AMOUNT
                                                CHECK (AMOUNT > 0),

                                            CONSTRAINT CK_BALANCE_BEFORE_NON_NEGATIVE
                                                CHECK (BALANCE_BEFORE >= 0),

                                            CONSTRAINT CK_BALANCE_AFTER_NON_NEGATIVE
                                                CHECK (BALANCE_AFTER >= 0)
);

CREATE INDEX IDX_BALANCE_OPERATION_ACCOUNT
    ON ACCOUNT_BALANCE_OPERATIONS (ACCOUNT_ID);

CREATE INDEX IDX_BALANCE_OPERATION_TRANSACTION
    ON ACCOUNT_BALANCE_OPERATIONS (TRANSACTION_REFERENCE);

CREATE INDEX IDX_BALANCE_OPERATION_CREATED
    ON ACCOUNT_BALANCE_OPERATIONS (CREATED_AT);