-- ============================================================
-- Enterprise Financial Data Platform
-- Account Service - Account Holds
-- ============================================================

CREATE TABLE ACCOUNT_HOLDS (
                               ACCOUNT_HOLD_ID NUMBER
                                   GENERATED BY DEFAULT AS IDENTITY,

                               HOLD_REFERENCE VARCHAR2(150) NOT NULL,

                               TRANSACTION_REFERENCE VARCHAR2(36) NOT NULL,

                               ACCOUNT_ID NUMBER NOT NULL,

                               AMOUNT NUMBER(19,2) NOT NULL,

                               HOLD_STATUS VARCHAR2(20) NOT NULL,

                               REQUEST_HASH VARCHAR2(64) NOT NULL,

                               DESCRIPTION VARCHAR2(255),

                               EXPIRES_AT TIMESTAMP NOT NULL,

                               CREATED_AT TIMESTAMP
                                   DEFAULT CURRENT_TIMESTAMP NOT NULL,

                               UPDATED_AT TIMESTAMP
                                   DEFAULT CURRENT_TIMESTAMP NOT NULL,

                               RESOLVED_AT TIMESTAMP,

                               VERSION NUMBER(19)
        DEFAULT 0 NOT NULL,

                               CONSTRAINT PK_ACCOUNT_HOLDS
                                   PRIMARY KEY (ACCOUNT_HOLD_ID),

                               CONSTRAINT UK_ACCOUNT_HOLD_REFERENCE
                                   UNIQUE (HOLD_REFERENCE),

                               CONSTRAINT FK_ACCOUNT_HOLD_ACCOUNT
                                   FOREIGN KEY (ACCOUNT_ID)
                                       REFERENCES ACCOUNTS (ACCOUNT_ID),

                               CONSTRAINT CK_ACCOUNT_HOLD_AMOUNT
                                   CHECK (AMOUNT > 0),

                               CONSTRAINT CK_ACCOUNT_HOLD_STATUS
                                   CHECK (
                                       HOLD_STATUS IN (
                                                       'ACTIVE',
                                                       'CAPTURED',
                                                       'RELEASED',
                                                       'EXPIRED'
                                           )
                                       ),

                               CONSTRAINT CK_ACCOUNT_HOLD_EXPIRATION
                                   CHECK (EXPIRES_AT > CREATED_AT),

                               CONSTRAINT CK_ACCOUNT_HOLD_RESOLUTION
                                   CHECK (
                                       (
                                           HOLD_STATUS = 'ACTIVE'
                                               AND RESOLVED_AT IS NULL
                                           )
                                           OR
                                       (
                                           HOLD_STATUS IN (
                                                           'CAPTURED',
                                                           'RELEASED',
                                                           'EXPIRED'
                                               )
                                               AND RESOLVED_AT IS NOT NULL
                                           )
                                       )
);

CREATE INDEX IDX_ACCOUNT_HOLD_ACCOUNT
    ON ACCOUNT_HOLDS (
                      ACCOUNT_ID
        );

CREATE INDEX IDX_ACCOUNT_HOLD_ACCOUNT_STATUS
    ON ACCOUNT_HOLDS (
                      ACCOUNT_ID,
                      HOLD_STATUS
        );

CREATE INDEX IDX_ACCOUNT_HOLD_TRANSACTION
    ON ACCOUNT_HOLDS (
                      TRANSACTION_REFERENCE
        );

CREATE INDEX IDX_ACCOUNT_HOLD_EXPIRATION
    ON ACCOUNT_HOLDS (
                      HOLD_STATUS,
                      EXPIRES_AT
        );

CREATE INDEX IDX_ACCOUNT_HOLD_CREATED
    ON ACCOUNT_HOLDS (
                      CREATED_AT
        );